Move the most of metadata into `PEP 621`-compliant `pyproject.toml`.
SheffieldML/GPy pull request #1006
Opened 2023-02-12 22:07 UTC by KOLANICH

2023-09-26 07:34 UTC, vnmabus commented
It partially overlaps with #975, I think.

2023-10-04 16:57 UTC, MartinBubel commented
I like it! What do you think @ekalosak @lawrennd ? Should merge this (after resolving conflicts etc) into the upcoming release or keep it for the subsequent one with more updates/qof-fixes?

2023-10-05 13:18 UTC, lawrennd commented
I'd be supportive of this.

2023-12-06 14:15 UTC, ekalosak commented
Yes pls update the branch and we need to merge it.

2024-03-26 07:29 UTC, MartinBubel requested changes
LGTM, only some minor things to be done

2024-03-26 07:29 UTC, MartinBubel commented on pyproject.toml
> +readme = "README.rst"
```suggestion
readme = "README.md"
```

2024-03-26 07:29 UTC, MartinBubel commented on pyproject.toml
> +    "Programming Language :: Python :: 3.9",
```suggestion
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
```

2024-03-26 07:29 UTC, MartinBubel commented on pyproject.toml
> +    "scipy>=1.3.0,<1.5.0; python_version < '3.6'",
```suggestion
    "scipy>=1.3.0,<=1.12.0"
```

2024-03-26 07:29 UTC, MartinBubel commented on pyproject.toml
> +    "paramz>=0.9.0",
```suggestion
    "paramz>=0.9.6",
```

2024-03-26 07:29 UTC, MartinBubel commented on pyproject.toml
> +    "matplotlib==3.0.0; python_version < '3.6'",
```suggestion
    "matplotlib>=3.3.4",
```

2024-06-06 10:55 UTC, merged